import type { Metadata } from 'next';

import Header from '@/src/components/modules/Header';


export const metadata: Metadata = {
  title: 'Courses page',
  description: 'Generated by create next app',
};

export default function CoursesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className='flex min-h-screen flex-col'>
      <Header />
      {children}
      {/*<Footer />*/}
    </div>
  );
}
