import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Course page',
  description: 'Generated by create next app',
};

export default function CoursePageLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className='flex min-h-screen flex-col'>
      {children}
    </div>
  );
}
